[tool.ruff]
line-length = 120
# [tool.ruff.lint]
select = ['E', 'F', 'UP', 'B', 'SIM', 'I']
ignore = ["E226", "E241", "E242", "W505", "Q000"]
[tool.ruff.format]
quote-style = "single"
[tool.pylsp-mypy]
enabled = false
